export const cases = [
 {id:'INC-001',slug:'authentication-attack',title:'Authentication',status:'PASS',proof:'Six failures. One correlation.',detail:'Six unique Security 4625 records crossed a five event, same account, five minute threshold.',telemetry:'Security 4625',detection:'Sigma + custom Wazuh 100201',mitre:'T1110',incident:'INC-B4FBF410',limit:'One nonexistent synthetic account; no successful login.',visual:'01  02  03  04  05  06 → 100201'},
 {id:'INC-002',slug:'powershell',title:'Encoded PowerShell',status:'PASS',proof:'One command. A complete evidence chain.',detail:'A benign encoded command appeared in PowerShell 4104 and Wazuh 92057, then in a documented VYOMRIX investigation.',telemetry:'PowerShell 4104 / Sysmon 1',detection:'Authored Sigma / built in Wazuh 92057',mitre:'T1059.001',incident:'INC-3DBE1D32',limit:'Benign marker only; no download or network action.',visual:'4104 → SIGMA → 92057 → DECISION'},
 {id:'INC-003',slug:'scheduled-task',title:'Scheduled task',status:'PASS',proof:'Creation observed. Cleanup verified.',detail:'Security 4698 and Wazuh 60228 recorded the visible task registration; the task was removed.',telemetry:'Security 4698 / PowerShell',detection:'Sigma / built in Wazuh 60228',mitre:'T1053.005',incident:'INC-CCEDCE5A',limit:'Task payload execution was not observed.',visual:'+ REGISTERED     − REMOVED'},
 {id:'INC-004',slug:'credential-access',title:'Credential access simulation',status:'PARTIAL',proof:'The denied request is the finding.',detail:'Windows denied a query only LSASS handle request. Wazuh recorded discovery; Sysmon Event 10 was absent.',telemetry:'PowerShell 4104',detection:'Wazuh 91815 discovery only',mitre:'T1003 · context only, not counted',incident:'INC-C8A3C71C',limit:'No credential read, memory dump, or Event 10. LSASS Sigma NOT_TRIGGERED.',visual:'QUERY DENIED    ◇    EVENT 10: 0'},
 {id:'INC-005',slug:'web-attack',title:'Host only web findings',status:'PASS',proof:'Kali requests. Verified application outcomes.',detail:'KALI-ATTACK sent controlled requests to an isolated purpose built app that recorded SQL injection bypass and traversal constrained to synthetic lab files.',telemetry:'Kali transcript / application JSON',detection:'Two application log Sigma rules',mitre:'AppSec · no Enterprise mapping',incident:'INC-7890B5F0',limit:'No Wazuh alert. The service was stopped and its request log was preserved.',visual:'KALI → sql-injection-bypass / path-traversal'},
 {id:'INC-006',slug:'exfiltration',title:'Synthetic data transfer',status:'PASS',proof:'489 bytes. Matching hashes.',detail:'WIN-LAB-01 transferred three synthetic files to the isolated Kali collector. Source staging and received payloads were removed.',telemetry:'PowerShell 4104 / Kali collector JSON',detection:'Archive staging Sigma / built in Wazuh 91819 context',mitre:'T1560.001 / T1048.003',incident:'INC-4C4C2C05',limit:'No Internet egress, command and control, or real data. Wazuh 91819 is supporting endpoint context, not a direct transfer detector.',visual:'WINDOWS SHA256 = KALI SHA256'},
];
export const stages = [
 {name:'Behavior',title:'Suspicious form. Harmless content.',source:'Preserved Windows record · INC-002',code:"Write-Output 'CyberLab-Phase3-Encoded-Benign'",conclusion:'The decoded command wrote a marker. It did not download content or generate network activity.',file:'incidents/INC-002-powershell/evidence/windows-events.json'},
 {name:'Telemetry',title:'Windows retained the decoded script.',source:'PowerShell Operational · Event 4104',code:'Event ID       4104\nRecord ID      2285\nTimestamp UTC  2026-09-13T06:12:17.1839479Z\nScript block   Write-Output \'CyberLab-Phase3-Encoded-Benign\'',conclusion:'Script block logging exposes the benign content. Process telemetry is preserved separately in the Wazuh event.',file:'incidents/INC-002-powershell/evidence/windows-events.json'},
 {name:'Sigma',title:'Authored logic, directly validated.',source:'encoded_powershell.yml · excerpt',code:'logsource:\n  product: windows\n  service: sysmon\ndetection:\n  selection:\n    EventID: 1\n    Image|endswith: \\powershell.exe\n    CommandLine|contains: -EncodedCommand\n  condition: selection',conclusion:'Administrative automation can also match. This authored Sigma selection is distinct from the built in Wazuh rule.',file:'detections/sigma/encoded_powershell.yml'},
 {name:'Wazuh',title:'A real platform alert.',source:'Wazuh built in rule 92057',code:'Alert    1789279933.4126869\nAgent    WIN-LAB-01 / 001\nAddress  192.168.56.20\nRule     92057 · built in\nLevel    12\nMITRE    T1059.001',conclusion:'The manager observed encoded PowerShell process creation. Original source timestamps are retained, without inferring cross-source ordering.',file:'incidents/INC-002-powershell/evidence/wazuh-alerts.json'},
 {name:'Investigation',title:'Evidence became analyst context.',source:'Preserved case documentation · VYOMRIX',code:'Incident  INC-3DBE1D32\nWorkflow  Timeline → evidence → analyst conclusion\nState     Contained\nMapping   T1059.001\nReport    Generated during verified lab workflow',conclusion:'The case documents investigation and reporting. A public UI screenshot is still pending; this is a textual case summary.',file:'incidents/INC-002-powershell/README.md'},
 {name:'Decision',title:'A bounded, defensible conclusion.',source:'INC-002 · containment, remediation and retest',code:'CONTAINMENT   One-shot process exited normally\nREMEDIATION   Retain script-block logging; review signed scripts\nRETEST        PASS: new 4104 and Wazuh 92057 evidence\nLIMIT         Benign behavior; no evasion-resistance claim',conclusion:'T1059.001 is directly evidenced. Contained is the analyst workflow state, not a claim that malware was removed.',file:'incidents/INC-002-powershell/RETEST.md'},
];
export const techniques = [ ['T1110','Brute Force','INC-001','Security 4625 / custom 100201'],['T1059.001','PowerShell','INC-002','4104 / Sysmon / Wazuh 92057'],['T1053.005','Scheduled Task','INC-003','Security 4698 / Wazuh 60228'],['T1560.001','Archive via Utility','INC-006','PowerShell 4104 / archive Sigma'],['T1048.003','Unencrypted non-C2 transfer','INC-006','Host-only HTTP receipt / matching SHA-256'] ];
