'use client';
import Link from 'next/link';
import {useEffect, useState} from 'react';
import {cases, stages, techniques} from './data';
import detections from './detection-validation.json';
const ruleContext:Record<string,[string,string]>={
 'failed_logon.yml':['Security 4625','User typos or stale service credentials.'],
 'failed_logon_burst.yml':['Security 4625 correlation','Password drift or repeated user mistakes.'],
 'encoded_powershell.yml':['Sysmon process creation','Administrative deployment scripts and guestcontrol helpers.'],
 'scheduled_task.yml':['Security 4698','Approved maintenance and software deployment tasks.'],
 'web_sql_injection.yml':['Instrumented application JSON','App-specific finding fields require schema review when ported.'],
 'web_path_traversal.yml':['Instrumented application JSON','Path normalization differences require contextual review.'],
 'powershell_archive_staging.yml':['PowerShell 4104','Backup, packaging and software distribution.'],
 'defender_change.yml':['Windows Defender Operational','Approved security administration.'],
 'office_shell.yml':['Process creation','Legitimate Office automation or add-ins.'],
 'lsass_process_access.yml':['Sysmon Event 10','Approved security and diagnostic tools.'],
};

function Badge({partial=false,children}:{partial?:boolean;children:React.ReactNode}) {return <span className={`lab-badge ${partial?'partial':''}`}>{partial?'◇':'■'} {children}</span>}
export function Architecture({compact=false}:{compact?:boolean}) {return <div className={`lab-architecture ${compact?'compact':''}`} aria-label="Lab architecture and telemetry path">
 <div className="lab-boundary"><span>VIRTUALBOX / HOST-ONLY</span><code>192.168.56.0/24</code></div>
 <div className="lab-nodes">
  <div className="lab-node operator"><small>01 / CONTROLLED OPERATOR</small><h3>KALI-ATTACK</h3><code>192.168.56.10</code><p>Available operator role.<br/>Not used in Phase 3.</p></div>
  <div className="lab-node"><small>02 / TELEMETRY CREATION</small><h3>WIN-LAB-01</h3><code>192.168.56.20</code><p>Sysmon · Windows Security<br/>PowerShell Operational<br/><strong>Wazuh Agent</strong></p></div>
  <div className="lab-node"><small>03 / COLLECTION + DETECTION</small><h3>WAZUH-MGR</h3><code>192.168.56.30</code><p>Wazuh Manager/API<br/>Verified TLS API<br/>Restricted SSH export</p></div>
  <div className="lab-node analyst"><small>04 / ANALYST WORKFLOW</small><h3>VYOMRIX</h3><code>Host loopback</code><p>Incident · Timeline · Evidence<br/>MITRE context · Report<br/><strong>Analyst decision</strong></p></div>
 </div><p className="lab-safety">Host: 192.168.56.1 <span>No bridged networking</span><span>Temporary NAT: maintenance only / disabled in attack mode</span></p>
 </div>}
function Metrics(){return <div className="lab-metrics">{[['06','Investigation scenarios','Six VYOMRIX workflows'],['10','Sigma rules authored','Portable detection logic'],['07','Directly validated','Preserved telemetry evidence'],['05','ATT&CK techniques','Direct evidence only']].map(([n,t,s])=><div key={n}><strong>{n}</strong><span>{t}</span><small>{s}</small></div>)}</div>}
function EvidenceViewer({index,setIndex}:{index:number;setIndex:(n:number)=>void}){const s=stages[index];return <div className="lab-viewer">
 <div className="lab-stage-nav" aria-label="Evidence stages">{stages.map((x,i)=><button key={x.name} aria-pressed={index===i} onClick={()=>setIndex(i)}><span>0{i+1}</span>{x.name}</button>)}</div>
 <div className={`lab-evidence ${index>=4?'decision':''}`} aria-live="polite"><div className="lab-evidence-head"><small>{s.source}</small><span>0{index+1} / 06</span></div><h3>{s.title}</h3><pre tabIndex={0}>{s.code}</pre><div className="lab-conclusion"><small>WHAT THIS PROVES</small><p>{s.conclusion}</p><a href={`/lab/evidence/${s.file}`} target="_blank" rel="noreferrer">Read preserved source ↗</a></div></div>
 </div>}
function DetectionLedger(){const [filter,setFilter]=useState('All');const rows=detections.rules.filter(r=>filter==='All'||(filter==='Validated'?r.validation==='VALIDATED':r.validation==='NOT_TRIGGERED'));return <>
 <div className="lab-taxonomy"><div><b>10</b><span>SIGMA AUTHORED</span></div><div><b>7</b><span>DIRECTLY VALIDATED</span></div><div><b>1</b><span>CUSTOM WAZUH</span></div><div><b>8</b><span>BUILT-IN OBSERVED</span></div></div><p className="lab-intro">Four cases contain real Wazuh alerts. All six demonstrate VYOMRIX incident workflows. INC-005 and INC-006 rely on application and endpoint evidence.</p>
 <div className="lab-filters" aria-label="Filter Sigma validation">{['All','Validated','Not triggered'].map(x=><button key={x} aria-pressed={filter===x} onClick={()=>setFilter(x)}>{x}</button>)}</div>
  <p className="lab-count" role="status">{rows.length} Sigma rules shown</p><div className="lab-ledger">{rows.map(r=><details key={r.id}><summary><span>{r.title}<small>Sigma · {r.mitre_tags.filter(t=>/attack\.t\d/.test(t)).map(t=>t.replace('attack.','').toUpperCase()).join(' / ')||'AppSec'}{r.validation!=='VALIDATED'?' · tag/context only':''}</small></span><Badge partial={r.validation!=='VALIDATED'}>{r.validation.replace('_',' ')}</Badge></summary><p>{r.evidence||'Syntax parsed; no direct trigger evidence.'}</p><p>Associated source: {r.references[0].split('/')[1]}</p><p>Log source: {ruleContext[r.file][0]}</p><p>False-positive considerations: {ruleContext[r.file][1]}</p><a href={`/lab/evidence/detections/sigma/${r.file}`}>Read authored rule ↗</a></details>)}</div>
 <div className="lab-wazuh"><div><small>AUTHORED / CUSTOM WAZUH</small><h3>100201</h3><p>Five failed logons, one account, five minutes. Validated in INC-001.</p></div><div><small>PLATFORM OBSERVED / BUILT-IN WAZUH</small><h3>Eight distinct IDs</h3><code>60122 · 60228 · 67027 · 91815<br/>91816 · 92004 · 92036 · 92057</code><p>Observed platform detections, counted separately from authored work.</p></div></div>
 </>}
export function LabExperience({demo=false}:{demo?:boolean}){
 const [stage,setStage]=useState(0);const [mode,setMode]=useState(30);const [offline,setOffline]=useState('');
 useEffect(()=>{if(!demo)return;const handler=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select,button,a')||e.ctrlKey||e.altKey||e.metaKey)return;if(e.key==='ArrowRight'){e.preventDefault();setStage(x=>(x+1)%stages.length)}if(e.key==='ArrowLeft'){e.preventDefault();setStage(x=>(x+stages.length-1)%stages.length)}if(e.key==='1')setMode(30);if(e.key==='2')setMode(90);if(e.key==='5')setMode(300);if(e.key==='Escape'){setMode(30);window.scrollTo(0,0)}const anchors:Record<string,string>={a:'architecture',c:'cases',d:'detections',l:'limitations'};if(anchors[e.key]){setMode(300);setTimeout(()=>document.getElementById(anchors[e.key])?.scrollIntoView(),0)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[demo]);
 async function prepareOffline(){setOffline('Preparing offline copy…');try{const response=await fetch('/lab/offline.html');if(!response.ok)throw new Error();const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='MKG-CyberLab-offline.html';a.click();URL.revokeObjectURL(url);setOffline('Offline file downloaded. Open it without Internet.')}catch{setOffline('Download unavailable. Retry while the local server is running.')}}
 return <main className={`lab-page ${demo?'demo-mode':''} ${demo&&mode===30?'demo-short':''}`}>
 <a className="lab-skip" href="#lab-content">Skip to content</a><header className="lab-nav"><Link href="/" className="lab-brand">MKG<span> / CYBERLAB</span></Link><nav aria-label="Lab navigation">{demo?<Link href="/lab">Full case study ↗</Link>:<><a href="#cases">Cases</a><a href="#detections">Detections</a><a href="#architecture">Architecture</a><Link href="/lab/demo">Career fair ↗</Link></>}</nav></header>
 {demo&&<div className="lab-demo-controls"><div>{[[30,'30 seconds'],[90,'90 seconds'],[300,'5 minutes']].map(([v,label])=><button key={v} aria-pressed={mode===v} onClick={()=>setMode(Number(v))}>{label}</button>)}</div><button onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void document.documentElement.requestFullscreen().catch(()=>setOffline('Fullscreen unavailable; use your browser fullscreen control.'))}}>Fullscreen</button><button onClick={prepareOffline}>Download offline edition ↓</button><span role="status">{offline}</span></div>}
 <div id="lab-content"><section className="lab-hero"><div className="lab-eyebrow"><span/> ISOLATED SECURITY ENGINEERING & DETECTION RANGE</div><div className="lab-hero-grid"><div><h1>MKG CYBER<br/><span>DEFENSE LAB</span></h1><p className="lab-lead">Controlled behavior.<br/>Real telemetry.<br/><em>Defensible decisions.</em></p><p className="lab-intro">Six investigations connect Windows evidence, authored detections and the analyst workflow.</p><div className="lab-actions"><a className="lab-primary" href="#flagship">Explore INC-002 <span>↗</span></a><a href="#evidence">Review the evidence ↓</a></div></div><div className="lab-hero-proof"><small>THE EVIDENCE PATH / INC-002</small>{['Controlled PowerShell','Windows · Event 4104','Authored Sigma','Wazuh · Rule 92057','VYOMRIX · Analyst decision'].map((s,i)=><div key={s} className={i===4?'amber':''}><span>0{i+1}</span><strong>{s}</strong></div>)}<p>Preserved evidence. Synthetic data.<br/>Five PASS cases. One deliberate PARTIAL.</p></div></div><Metrics/></section>
 <section className="lab-section" id="architecture"><div className="lab-section-heading"><small>01 / SYSTEM BOUNDARY</small><h2>Isolated by design.</h2><p>Each system has a defined role. Every connection has a documented purpose.</p></div><Architecture compact={demo}/></section>
 <section className="lab-section" id="flagship"><div className="lab-section-heading"><small>02 / FLAGSHIP INVESTIGATION</small><Badge>INC-002 · PASS</Badge><h2>Follow one signal.<br/><span>Inspect every decision.</span></h2><p>A benign encoded PowerShell command remained visible through the complete analyst path.</p></div><EvidenceViewer index={stage} setIndex={setStage}/><div className="lab-proof-foot"><span>T1059.001 / POWERSHELL</span><span>WAZUH 92057 / BUILT-IN</span><span>SIGMA / VALIDATED</span></div></section>
 {(!demo||mode===300)&&<>
 <section className="lab-section" id="cases"><div className="lab-section-heading"><small>03 / INVESTIGATION RECORD</small><h2>Six cases.<br/><span>Evidence over assumption.</span></h2><p>Every investigation includes its detection path, analyst conclusion and limits.</p></div><div className="lab-cases">{cases.map((c,i)=><article key={c.id} className={`lab-case case-${i+1}`}><div className="lab-case-top"><code>{c.id}</code><Badge partial={c.status==='PARTIAL'}>{c.status}</Badge></div><h3>{c.title}</h3><p className="lab-case-proof">{c.proof}</p><div className="lab-case-visual" aria-hidden="true">{c.visual}</div><p>{c.detail}</p><dl><dt>Telemetry</dt><dd>{c.telemetry}</dd><dt>Detection</dt><dd>{c.detection}</dd><dt>Technique</dt><dd>{c.mitre}</dd><dt>Workflow</dt><dd>{c.incident} · Contained</dd></dl><details><summary>Evidence & limitation</summary><p>{c.limit}</p><a href={`/lab/evidence/incidents/${c.id}-${c.slug}/README.md`}>Preserved case documentation ↗</a></details><Link className="lab-case-link" href={`/lab/incidents/${c.slug}`}>Open investigation ↗</Link></article>)}</div></section>
 <section className="lab-section" id="detections"><div className="lab-section-heading"><small>04 / DETECTION ENGINEERING</small><h2>Authored. Validated.<br/><span>Clearly distinguished.</span></h2><p>Authored Sigma, custom correlation and observed platform rules retain separate counts.</p></div><DetectionLedger/></section>
 <section className="lab-section" id="mitre"><div className="lab-section-heading"><small>05 / MITRE ATT&CK</small><h2>Five evidenced techniques.</h2></div><div className="lab-mitre">{techniques.map(([id,name,incident,source])=><div key={id}><code>{id}</code><h3>{name}</h3><span>{incident}</span><p>{source}</p><Badge>EVIDENCED</Badge></div>)}</div><p className="lab-warning">◇ T1003 is context only. The LSASS query was denied, Event 10 was absent, and credential dumping is not counted.</p></section>
 </>}
 {(!demo||mode!==30)&&<section className="lab-section" id="evidence"><div className="lab-section-heading"><small>06 / VYOMRIX</small><h2>The analyst interface<br/><span>of the lab.</span></h2><p>Wazuh supplies telemetry and detection. VYOMRIX supports the investigation, timeline, evidence and report workflow.</p></div><div className="lab-showcase"><div><small>PRESERVED CASE RECORD / TEXTUAL SUMMARY</small><h3>INC-3DBE1D32</h3><p>Encoded PowerShell · WIN-LAB-01</p><ol><li>Original Wazuh alert referenced</li><li>Timeline and analyst context recorded</li><li>Evidence linked to the investigation</li><li>T1059.001 mapping documented</li><li>Contained state and report generated</li></ol><a href="/lab/evidence/incidents/INC-002-powershell/README.md">Read case documentation ↗</a></div><div className="lab-pending"><span>＋</span><small>EVIDENCE CAPTURE PENDING</small><p>Provider health, real agent, alert detail, incident and timeline/report UI captures.</p><p>Text evidence is available. No simulated dashboard is shown.</p></div></div></section>}
 {(!demo||mode===300)&&<><section className="lab-section"><div className="lab-section-heading"><small>07 / ENGINEERING JUDGEMENT</small><h2>The constraints<br/><span>are part of the work.</span></h2></div><div className="lab-decisions">{[['A smaller Wazuh footprint','Manager/API and restricted evidence export fit the 15.38 GiB host. The full indexer/dashboard stack was omitted.'],['A deliberate network boundary','Host-only adapters and disabled maintenance NAT kept controlled scenarios inside the range.'],['Seven validated means seven','Three Sigma rules remain NOT_TRIGGERED. Syntax validation alone is not behavioral proof.'],['Negative evidence stays visible','INC-004 stopped at a denied query. No credential harvesting was performed to manufacture a successful result.']].map(([t,p],i)=><div key={t}><span>0{i+1}</span><h3>{t}</h3><p>{p}</p></div>)}</div></section><section className="lab-section lab-limits" id="limitations"><small>08 / ENGINEERING SCOPE</small><h2>Know the boundary.</h2><p>This is an isolated laboratory, not production SOC infrastructure. Sequential operation respects a resource-constrained host.</p><ul><li>INC-004 is PARTIAL: no credential read and no Sysmon Event 10.</li><li>Three of ten Sigma rules remain NOT_TRIGGERED.</li><li>INC-005 and INC-006 have no Wazuh alert for their primary behavior.</li><li>Scheduled-task payload execution was not observed.</li><li>ABHEDYA is not integrated; its comparison was skipped.</li></ul></section></>}
 <footer className="lab-footer"><h2>Review the work.</h2><div><a href="/lab/evidence/incidents/INC-002-powershell/README.md">Flagship documentation ↗</a><Link href="/lab/demo">Offline career-fair mode ↗</Link><Link href="/">Mithil’s portfolio ↗</Link><a href="https://github.com/mithilkg10/MITHILKG-PORTFOLIO">Portfolio source ↗</a></div><p>CyberLab and VYOMRIX public repository URLs pending. All counts use preserved evidence: 8 built-in Wazuh IDs + 1 custom rule.</p></footer></div>
 </main>
}
