import Link from 'next/link';
import type {Metadata} from 'next';
import {cases} from '../lab/data';
import {RangeMark} from '@/components/ui/RangeMark';
import {RangeProof} from '@/components/sections/RangeFeature';
export const metadata:Metadata={title:'Evidence Vault | MKG Cyber Defense Lab',description:'Six documented investigations with preserved telemetry, detection logic, containment and retests.',alternates:{canonical:'/evidence'}};
const paths=[
 {origin:'Windows local controlled failures',target:'WIN-LAB-01',kali:'NOT APPLICABLE: preflight only; no authentication attempt',wazuh:'Custom correlation 100201',containment:'Synthetic failures stopped',retest:'Correlation and records verified',flow:['Windows local failures','Security 4625','Sigma correlation','Wazuh 100201','VYOMRIX','Containment decision']},
 {origin:'Windows local PowerShell',target:'WIN-LAB-01',kali:'NOT APPLICABLE: endpoint local execution',wazuh:'Observed alert 92057',containment:'Benign process exited',retest:'New 4104 and Wazuh evidence',flow:['Windows PowerShell','PowerShell 4104 / process event','Sigma','Wazuh 92057','VYOMRIX','Contained']},
 {origin:'Windows local task registration',target:'WIN-LAB-01',kali:'NOT APPLICABLE: endpoint local execution',wazuh:'Observed alert 60228',containment:'Task removed',retest:'Removal verified; payload execution not observed',flow:['Windows task registration','Security 4698','Sigma','Wazuh 60228','VYOMRIX','Task removal']},
 {origin:'Windows local query only access request',target:'LSASS on WIN-LAB-01',kali:'NOT APPLICABLE: no collection or transfer',wazuh:'91815 discovery context only',containment:'Access denied; no credential read',retest:'Event 10 absent; Sigma NOT_TRIGGERED',flow:['Windows query','Access denied','PowerShell discovery','Wazuh 91815 context','VYOMRIX','PARTIAL conclusion']},
 {origin:'KALI-ATTACK · 192.168.56.10',target:'Synthetic host app · 192.168.56.1:8085',kali:'ADVERSARY SOURCE',wazuh:'No alert; application evidence retained',containment:'Port 8085 closed; request log preserved',retest:'Service stop verified',flow:['Kali requests','Synthetic host application','Application records','AppSec Sigma','VYOMRIX','Service stopped']},
 {origin:'WIN-LAB-01 · 192.168.56.20',target:'Kali collector · 192.168.56.10:8090',kali:'SUPPORTING COLLECTOR',wazuh:'91819 endpoint context; no direct transfer detector',containment:'Receiver stopped; payload copies removed',retest:'Matching hashes; port 8090 closed',flow:['Windows synthetic archive','489 byte isolated transfer','Kali collector','PowerShell 4104 / Wazuh 91819 context','VYOMRIX','Payload removal']}
];
export default function Evidence(){return <main className="evidence-vault"><a className="vault-skip" href="#investigations">Skip to investigations</a><header className="vault-nav"><Link href="/" className="vault-brand"><RangeMark/>MKG <span>/ EVIDENCE</span></Link><nav aria-label="Evidence navigation"><Link href="/lab">Interactive Range ↗</Link><Link href="/lab/demo?duration=90">90 Second Demo</Link></nav></header>
<section className="vault-intro"><RangeMark className="vault-watermark"/><p className="range-kicker">CAPTURED IN ISOLATED LAB · SANITIZED FOR PUBLIC RELEASE</p><h1>Inspect the<br/><em>engineering record.</em></h1><p>Six investigations. Original telemetry, authored detections and documented decisions. Every case below links to the preserved public record used by the evidence replay.</p><RangeProof/><p className="vault-provenance">Evidence baseline: <code>523a3f7</code> · Five PASS cases · One deliberate PARTIAL · Screenshot coverage PARTIAL</p></section>
<section id="investigations" className="vault-cases" aria-label="Six investigations">{cases.map((c,i)=>{const p=paths[i];const base=`/lab/evidence/incidents/${c.id}-${c.slug}`;return <article key={c.id} className="vault-case"><div className="vault-case-heading"><div><small>{c.id}</small><h2>{c.title}</h2></div><strong className={`vault-status ${c.status==='PARTIAL'?'partial':''}`}>{c.status==='PARTIAL'?'◇':'✓'} {c.status}</strong></div><p>{c.detail}</p><ol className="vault-flow" aria-label={`${c.id} verified evidence path`}>{p.flow.map((s,n)=><li key={s}><small>{String(n+1).padStart(2,'0')}</small>{s}</li>)}</ol><dl>{Object.entries({'Adversary source':p.origin,'Target':p.target,'Kali role':p.kali,'Telemetry':c.telemetry,'Detection':c.detection,'Wazuh status':p.wazuh,'VYOMRIX status':`${c.incident} · Contained workflow`,'MITRE':c.mitre,'Containment':p.containment,'Retest':p.retest}).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="vault-limit"><b>Evidence boundary:</b> {c.limit}</p><nav className="vault-links" aria-label={`${c.id} evidence controls`}><Link href={`/lab/incidents/${c.slug}`}>View Case ↗</Link><a href={`${base}/TELEMETRY.md`}>View Telemetry</a><a href={`${base}/DETECTION.md`}>View Detection</a><a href={`${base}/TIMELINE.md`}>View Timeline</a><a href={`https://github.com/mithilkg10/MKG-Cyber-Defense-Lab/tree/523a3f760db2bdce4d487e87c4109a66e901abea/incidents/${c.id}-${c.slug}`}>View Source</a></nav></article>})}</section><footer className="vault-footer">SANITIZED LAB EVIDENCE · EVIDENCE REPLAY SOURCE <Link href="/lab">Open safe replay ↗</Link></footer></main>}
