import {test,expect} from '@playwright/test';
for(const [name,width,height] of [['desktop',1440,1000],['laptop',1280,900],['tablet',768,1024],['mobile',390,844]] as const){
 test(`portfolio transformation ${name}`,async({page})=>{
 await page.setViewportSize({width,height});await page.emulateMedia({reducedMotion:'reduce'});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('div.fixed[class*="z-[100]"]')).toHaveCount(0,{timeout:15000});
 const badge=page.getByRole('link',{name:'MKG Cyber Range: open isolated lab'});await expect(badge).toBeVisible();await expect(badge).toHaveAttribute('href','/lab');
 if(width>=1024){await expect(page.getByRole('link',{name:'CYBER LAB',exact:true})).toBeVisible();}else{await page.getByRole('button',{name:'Toggle menu'}).click();await expect(page.locator('#mobile-navigation').getByRole('link',{name:'CYBER LAB',exact:true})).toBeVisible();await page.getByRole('button',{name:'Toggle menu'}).click();}
 await expect(page.locator('#lab')).toHaveCount(1);await page.locator('#lab').scrollIntoViewIfNeeded();await expect(page.getByRole('heading',{name:'CYBER DEFENSE RANGE',exact:true})).toBeVisible();await expect(page.locator('#lab')).toContainText('9');
 await page.locator('#projects').scrollIntoViewIfNeeded();await expect(page.getByRole('heading',{name:'MKG Cyber Defense Lab',exact:true})).toBeVisible();
 await page.locator('#assessments').scrollIntoViewIfNeeded();await page.getByRole('button',{name:'Security Audits',exact:true}).click();await page.getByRole('button',{name:'CyberLab Evidence',exact:true}).click();await expect(page.getByRole('link',{name:'Open Evidence Vault'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.evaluate(()=>scrollTo(0,0));await expect.poll(()=>page.evaluate(()=>scrollY)).toBe(0);await page.screenshot({path:`lab-test-results/home-transformation-${name}.png`});
 await page.goto('/evidence');await expect(page.locator('.vault-case')).toHaveCount(6);await expect(page.locator('.vault-case').nth(3)).toContainText('PARTIAL');await expect(page.locator('.vault-case').nth(4)).toContainText('ADVERSARY SOURCE');await expect(page.locator('.vault-case').nth(5)).toContainText('SUPPORTING COLLECTOR');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();await page.screenshot({path:`lab-test-results/evidence-transformation-${name}.png`});expect(errors).toEqual([]);
 });
}
test('vault evidence links and keyboard access',async({page,request})=>{await page.goto('/evidence');await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Skip to investigations'})).toBeFocused();const links=await page.locator('.vault-links a').evaluateAll(a=>a.map(e=>e.getAttribute('href')!));for(const href of links.filter(h=>h.startsWith('/'))){expect((await request.get(href)).status(),href).toBe(200);}await page.goto('/lab/demo?duration=90');await expect(page.getByRole('button',{name:'90 seconds',exact:true})).toHaveAttribute('aria-pressed','true');});
